// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2uFZ_yq_haQohfi_PFK8o1b2Bf2BJ07g',
    appId: '1:69059626570:web:3e35138672442e287f08b3',
    messagingSenderId: '69059626570',
    projectId: 'assignment52-887a1',
    authDomain: 'assignment52-887a1.firebaseapp.com',
    storageBucket: 'assignment52-887a1.firebasestorage.app',
    measurementId: 'G-KVJFRDKBW1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZ0DnbCtDC6CQtHttlH5I2kERci9H87PI',
    appId: '1:69059626570:android:bd6cac9c8ff6aa817f08b3',
    messagingSenderId: '69059626570',
    projectId: 'assignment52-887a1',
    storageBucket: 'assignment52-887a1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6-dj65qAvhGy4XRRMhpW0HueEJ8LFna0',
    appId: '1:69059626570:ios:7ba032da4c6b7ef07f08b3',
    messagingSenderId: '69059626570',
    projectId: 'assignment52-887a1',
    storageBucket: 'assignment52-887a1.firebasestorage.app',
    iosBundleId: 'com.example.assignment58real',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6-dj65qAvhGy4XRRMhpW0HueEJ8LFna0',
    appId: '1:69059626570:ios:7ba032da4c6b7ef07f08b3',
    messagingSenderId: '69059626570',
    projectId: 'assignment52-887a1',
    storageBucket: 'assignment52-887a1.firebasestorage.app',
    iosBundleId: 'com.example.assignment58real',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2uFZ_yq_haQohfi_PFK8o1b2Bf2BJ07g',
    appId: '1:69059626570:web:f7a9115833cfb2157f08b3',
    messagingSenderId: '69059626570',
    projectId: 'assignment52-887a1',
    authDomain: 'assignment52-887a1.firebaseapp.com',
    storageBucket: 'assignment52-887a1.firebasestorage.app',
    measurementId: 'G-CXR7S5K262',
  );
}
